version: '3.8'
services:

  app:
    image: ${APP_IMAGE}  # TODO 배포 시 .env 추가
    build: .
    restart: always
    # platform: linux/amd64 # m1 환경에서만
    ports:
      - "${APP_LOCAL_PORT}:${APP_SERVER_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}  # TODO 배포 시 .env 추가
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    env_file:
      - .env